# permissions for end users to edit virtplugins.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtplugins-editor-role
rules:
- apiGroups:
  - plumber.k8s.pf9.io
  resources:
  - virtplugins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - plumber.k8s.pf9.io
  resources:
  - virtplugins/status
  verbs:
  - get
