apiVersion: plumber.k8s.pf9.io/v1
kind: HostNetworkTemplate
metadata:
  name: hostconfig-kernel-enp3
spec:
  # Add fields here
  nodeSelector:
    feature.node.kubernetes.io/network-sriov.capable: "true"
    testlabelA: "123"
  interfaceConfig:
    - name: enp3s0f1
      # MTU can be set either here OR in sriovConfig. Affects PF + any VFs under it
      mtu: 9000
      ipv4:
        # Addresses reflect final desired state - anything not present will be deleted
        address: 
          - 192.168.193.1/24
          - 192.168.194.1/24
  sriovConfig:
    - pfName: enp3s0f1
      numVfs: 4
      vfDriver: vfio-pci
      mtu: 9000
    - pfName: enp3s0f0
      numVfs: 4
      vfDriver: ixgbevf
