apiVersion: plumber.k8s.pf9.io/v1
kind: NetworkPlugins
metadata:
  name: networkplugins-sample11
spec:
  # Add fields here
  #registryPrefix: "localhost:5100"
  plugins:
    hostPlumber:
      imagePullPolicy: "Always"
    nodeFeatureDiscovery: {}
    multus: {}
    whereabouts: {}
    # SRIOV actually consists of two plugins - the CNI, and the device-plugin
    sriov: {}
    #ovs: {}
