apiVersion: plumber.k8s.pf9.io/v1
kind: NetworkPlugins
metadata:
  name: networkplugins-sample11
spec:
  # Add fields here
  plugins:
    hostPlumber:
      hostPlumberImage: "platform9/luigi-plumber:v0.2"
    nodeFeatureDiscovery: {}
    multus: {}
    whereabouts: {}
    #sriov: {}
